# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaempleadora',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pensionado',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
