# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20161106_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaempleadora',
            name='ciudadMunicipio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empresaempleadora',
            name='departamento',
            field=models.CharField(max_length=30),
        ),
    ]
