# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20161107_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_emp', to='payment.EmpresaEmpleadora'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empl_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pensionado',
            name='tarifaEspecial',
            field=models.CharField(blank=True, choices=[('1', 'ACTIVIDADES ALTO RIESGO'), ('2', 'SENADOR'), ('3', 'CTI'), ('4', 'AVIADOR')], max_length=1),
        ),
    ]
