# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='pensionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='payment.Pensionado'),
        ),
    ]
