# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20161107_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionado',
            name='empresaEmpleadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_emp', to='payment.EmpresaEmpleadora'),
        ),
    ]
