# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20161107_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PagoAporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('01', 'SALUD'), ('02', 'PENSION'), ('03', 'RIESGOS LABORALES')], max_length=1)),
                ('periodoPago', models.CharField(max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPago', models.DateField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Banco')),
                ('pensionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='payment.Pensionado')),
            ],
        ),
    ]
